# Generated by Django 5.1.3 on 2026-01-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_batch_id_inventoryitem_expiry_date_and_more'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldstorageinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='coldstorageinventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='coldstorageinventory',
            name='cartons',
            field=models.PositiveIntegerField(default=0, help_text='Number of full cartons in storage.'),
        ),
        migrations.AddField(
            model_name='coldstorageinventory',
            name='loose_units',
            field=models.PositiveIntegerField(default=0, help_text='Loose packets not in cartons.'),
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size_ml', models.PositiveIntegerField(help_text='Size of each packet in ml (e.g. 250, 500)')),
                ('packets_per_carton', models.PositiveIntegerField(help_text='Number of packets per carton (e.g. 24, 12)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this packaging is for.', on_delete=django.db.models.deletion.PROTECT, related_name='packagings', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['product', 'pack_size_ml'],
                'unique_together': {('product', 'pack_size_ml', 'packets_per_carton')},
            },
        ),
        migrations.AddField(
            model_name='coldstorageinventory',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Packaging type for this inventory record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='storage.packaging'),
        ),
    ]
