# Generated by Django 5.1.3 on 2026-01-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_coldstorageinventory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='bulk_price_per_carton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: bulk price applied per carton for wholesale purchases.', max_digits=10, null=True),
        ),
    ]
