# Generated by Django 5.1.3 on 2026-01-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_batch_id_inventoryitem_expiry_date_and_more'),
        ('storage', '0003_packaging_bulk_price_per_carton'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredStockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartons', models.IntegerField(default=0)),
                ('loose_units', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('batch_id', models.CharField(blank=True, max_length=50)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('audit_notes', models.TextField(blank=True)),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.packaging')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storagelocation')),
            ],
        ),
    ]
