# Generated by Django 5.1.3 on 2026-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_expiredstockinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('cold_room', 'Cold Room'), ('fermentation_zone', 'Fermentation Chill Zone'), ('atms_Storage', 'ATMs Storage'), ('ambient_store', 'Ambient Store'), ('blast_chiller', 'Blast Chiller'), ('dry_store', 'Dry Storage'), ('quarantine', 'Spoilt / Quarantine Zone')], default='cold_room', max_length=30),
        ),
    ]
