# Generated by GitHub Copilot on 2026-01-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=120, unique=True)),
                ("category", models.CharField(max_length=60)),
                ("message", models.TextField()),
                ("model_label", models.CharField(blank=True, max_length=120)),
                ("record_id", models.CharField(blank=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("auto_resolved", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-detected_at"]},
        ),
    ]
