# Generated by Django 5.1.3 on 2026-01-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataqualityalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'permissions': [('view_dashboard', 'Can access main dashboard')]},
        ),
    ]
