# Generated by Django 4.2.27 on 2025-12-11 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('breed', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('monitor', 'Monitor'), ('sick', 'Needs Attention')], default='healthy', max_length=20)),
                ('stall_location', models.CharField(blank=True, max_length=50)),
                ('daily_capacity_litres', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['cow_id'],
            },
        ),
        migrations.CreateModel(
            name='MilkYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('morning_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evening_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('storage_tank', models.CharField(blank=True, max_length=40)),
                ('storage_level_percentage', models.PositiveIntegerField(default=0)),
                ('quality_score', models.PositiveSmallIntegerField(default=100)),
                ('quality_notes', models.TextField(blank=True)),
                ('total_yield', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='production.cow')),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
                'unique_together': {('cow', 'recorded_at')},
            },
        ),
    ]
