# Generated by Django 4.2.27 on 2025-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_cow_id_alter_milkyield_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkyield',
            old_name='evening_yield',
            new_name='yield_litres',
        ),
        migrations.RemoveField(
            model_name='milkyield',
            name='morning_yield',
        ),
        migrations.AddField(
            model_name='milkyield',
            name='quality_grade',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('low', 'Low')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='milkyield',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='milkyield',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=85, editable=False),
        ),
        migrations.AlterField(
            model_name='milkyield',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='milkyield',
            name='storage_level_percentage',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='milkyield',
            name='storage_tank',
            field=models.CharField(choices=[('Tank A', 'Tank A'), ('Tank B', 'Tank B'), ('Tank C', 'Tank C')], default='Tank A', max_length=40),
        ),
    ]
