# Generated by Django 4.2.27 on 2025-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_evening_yield_milkyield_yield_litres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkyield',
            options={'ordering': ['-recorded_at', '-created_at'], 'permissions': [('approve_milk', 'Can approve or reject milk quality')]},
        ),
        migrations.AlterField(
            model_name='milkyield',
            name='storage_tank',
            field=models.CharField(choices=[('Tank A', 'Tank A'), ('Tank B', 'Tank B'), ('Tank C', 'Tank C'), ('Spoilt Tank', 'Spoilt Tank')], default='Tank A', max_length=40),
        ),
    ]
