# Generated by Django 4.2.27 on 2025-12-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorytransaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0004_alter_milkyield_options_alter_milkyield_storage_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_price', to='inventory.inventoryitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_name'],
                'permissions': [('view_productpricechangelog', 'Can view product price change logs')],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_price_change_logs', to=settings.AUTH_USER_MODEL)),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='production.productprice')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
