# Generated by Django 4.2.27 on 2025-12-12 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0005_productprice_productpricechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkyield',
            name='raw_test_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkyield',
            name='tank_test_latest_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('atm', 'Fresh Milk ATM'), ('esl', 'ESL Milk'), ('yogurt', 'Yogurt'), ('mala', 'Mala'), ('ghee', 'Ghee')], max_length=20)),
                ('sku', models.CharField(max_length=30)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produced_at', models.DateTimeField(auto_now_add=True)),
                ('moved_to_lab', models.BooleanField(default=False)),
                ('milk_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='production.milkyield')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-produced_at'],
            },
        ),
    ]
