# Generated by Django 4.2.27 on 2025-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_productionbatch_source_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkyield',
            name='storage_tank',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Tank A', 'Tank A'), ('Tank B', 'Tank B'), ('Tank C', 'Tank C'), ('Spoilt Tank', 'Spoilt Tank')], default='Unassigned', max_length=40),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='source_tank',
            field=models.CharField(choices=[('Tank A', 'Tank A'), ('Tank B', 'Tank B'), ('Tank C', 'Tank C'), ('Spoilt Tank', 'Spoilt Tank')], max_length=40),
        ),
    ]
