# Generated by Django 6.0 on 2026-01-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_collection_windows_and_batch_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milkyield",
            name="raw_test_approved",
        ),
    ]
