# Generated by Django 6.0 on 2026-01-02 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_storagelocation_coldstorageinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldstorageinventory',
            name='production_batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_storage_record', to='production.productionbatch'),
        ),
    ]
