# Generated by Django 5.1.3 on 2026-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_milkyield_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='bulk_price_per_carton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
