# Generated by Django 5.1.3 on 2026-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_productprice_bulk_price_per_carton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='product_type',
            field=models.CharField(choices=[('atm', 'Fresh Milk ATM'), ('raw', 'Raw Milk (Bulk)'), ('esl', 'ESL Milk'), ('yogurt', 'Yogurt'), ('mala', 'Mala'), ('ghee', 'Ghee')], max_length=20),
        ),
    ]
