# Generated by Django 5.1.3 on 2026-01-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_inventoryitem_batch_id_inventoryitem_expiry_date_and_more'),
        ('storage', '0005_alter_storagelocation_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('seller_type', models.CharField(choices=[('distributor', 'Distributor'), ('retailer', 'Retailer'), ('agent', 'Agent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(choices=[('served', 'Served'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], max_length=10)),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.packaging')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
    ]
