# Generated by Django 4.2.27 on 2025-12-11 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('unit', models.CharField(choices=[('L', 'Litres'), ('KG', 'Kilograms'), ('UNIT', 'Units')], default='L', max_length=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
