# Generated by Django 4.2.27 on 2025-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_id_alter_inventorytransaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
