# Generated by Django 4.2.27 on 2025-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='flavor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_category',
            field=models.CharField(blank=True, choices=[('raw', 'Raw Milk Storage'), ('atm', 'Fresh Milk ATM'), ('esl', 'ESL Milk'), ('yogurt', 'Yogurt'), ('mala', 'Mala'), ('ghee', 'Ghee')], max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='size_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
