# Generated by Django 4.2.27 on 2025-12-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_brand_inventoryitem_flavor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'permissions': [('dispatch_product', 'Can dispatch finished products')]},
        ),
    ]
