# Generated by Django 4.2.27 on 2025-12-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorytransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
