# Generated by Django 4.2.27 on 2025-12-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_salestransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesTransaction',
        ),
    ]
