# Generated by Django 6.0 on 2026-01-01 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0010_collection_windows_and_batch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBatchApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_batch_approvals', to=settings.AUTH_USER_MODEL)),
                ('production_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_approval', to='production.productionbatch')),
            ],
            options={
                'ordering': ['-approved_at'],
                'permissions': [('approve_milk_batch', 'Can approve or reject milk batches'), ('issue_expiry', 'Can issue expiry dates for approved batches')],
            },
        ),
        migrations.CreateModel(
            name='RawMilkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('milk_yield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_test', to='production.milkyield')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='TankBatchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('milk_yield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_tests', to='production.milkyield')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
