# Generated by Django 4.2.27 on 2025-12-12 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0005_productprice_productpricechangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('bacteria', 'Bacteria Count'), ('acidity', 'Acidity Level'), ('fat', 'Fat Content'), ('protein', 'Protein Content'), ('adulteration', 'Adulteration Check')], max_length=40)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('reject', 'Reject'), ('conditional', 'Conditional Approval')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('milk_yield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='production.milkyield')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='LabBatchApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_batch_approvals', to=settings.AUTH_USER_MODEL)),
                ('milk_yield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_approval', to='production.milkyield')),
            ],
            options={
                'ordering': ['-approved_at'],
                'permissions': [('approve_milk_batch', 'Can approve or reject milk batches'), ('issue_expiry', 'Can issue expiry dates for approved batches')],
            },
        ),
    ]
