# Generated by Django 4.2.27 on 2025-12-12 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_milkyield_raw_test_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMilkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('milk_yield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_test', to='production.milkyield')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='TankBatchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('milk_yield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_tests', to='production.milkyield')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.RemoveField(
            model_name='labbatchapproval',
            name='milk_yield',
        ),
        migrations.AddField(
            model_name='labbatchapproval',
            name='production_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_approval', to='production.productionbatch'),
        ),
        migrations.DeleteModel(
            name='MilkTest',
        ),
    ]
