# Generated by Django 6.0 on 2026-01-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        ('production', '0010_collection_windows_and_batch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yields', models.ManyToManyField(blank=True, related_name='batches', to='production.milkyield')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('fat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snf_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contaminants', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lab.batch')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
