# Generated by Django 6.0 on 2026-01-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_batch_batchtest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RawMilkTest",
        ),
    ]
