# Generated by Django 6.0 on 2026-01-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_storagelocation_coldstorageinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldstorageinventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='coldstorageinventory',
            name='production_batch',
        ),
        migrations.DeleteModel(
            name='StorageLocation',
        ),
        migrations.DeleteModel(
            name='ColdStorageInventory',
        ),
    ]
