# Generated by Django 4.2.27 on 2025-12-12 12:11

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_salestransaction'),
        ('sales', '0002_alter_salesitem_id_alter_salestransaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='walk_in_customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='transaction_id',
            field=models.CharField(default=sales.models.generate_transaction_id, editable=False, max_length=12, unique=True),
        ),
    ]
