# Generated by Django 5.1.3 on 2026-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_salestransaction_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='bulk_price_per_carton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='cartons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='loose_units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
