# Generated by Django 5.1.3 on 2026-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesitem_bulk_price_per_carton_salesitem_cartons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='bulk_price_source',
            field=models.CharField(blank=True, choices=[('packaging', 'Packaging'), ('product', 'ProductPrice'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='sold_as',
            field=models.CharField(choices=[('unit', 'Unit'), ('carton', 'Carton')], default='unit', max_length=10),
        ),
    ]
