# Generated by Django 5.1.3 on 2026-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesitem_bulk_price_source_salesitem_sold_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sold_as',
            field=models.CharField(choices=[('unit', 'Unit'), ('carton', 'Carton')], max_length=10),
        ),
    ]
