# Generated by Django 6.0 on 2026-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesitem_sold_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sold_as',
            field=models.CharField(choices=[('unit', 'Unit'), ('carton', 'Carton')], default='unit', max_length=10),
        ),
    ]
